### ISSUE TITLE
Instructions for running locally

### ISSUE THREAD

**Issue by atn34** [scottbarron1313/sandbox_climbs#1]
@scottbarron1313 can you add instructions for running locally? Thanks!

**Comment by scottbarron1313** [comment]
@atn34 To run, you need to have a postgres sever set up locally (in boulder_collective.py lines 17-20 and 58 connect to the server). The postgres server needs two tables, "logins" (with a username and password for you) and "boulders". Right now Dustin and I have both tables under the database sandbox, but if you wanted to change that you could. I think that's the only real dependency, then just do python boulder_collective.py and it'll give you a local address to put in your browser so you can see what the page looks like. 

Oh, and the tables are setup like this:
logins:
 username | password 
----------+----------
 sbarron  | test

boulders:
 climber |       climb        | grade | latitude  |  longitude  
---------+--------------------+-------+-----------+-------------
 Scott   | Monks Roof         | v11   |  38.80051 | -120.139052
 Scott   | Midnight Lightning | v8    | 37.741713 | -119.603534
 Scott   | Work               | Fuck  |   37.3906 |    -122.031

You can replace the data with whatever you want.
